# Generated by Django 4.1.13 on 2023-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('decision', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
