# Generated by Django 5.0 on 2024-01-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0004_alter_robodecisionmodel_id_alter_tradingdecision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('decision', models.CharField(max_length=10)),
                ('result', models.BooleanField()),
                ('decision_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
